package cn.hualand.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.hualand.entity.UserInfoEntity;
import cn.hualand.entity.RecordEntity;

import cn.hualand.dao.UserInfoEntityDao;
import cn.hualand.dao.RecordEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoEntityDaoConfig;
    private final DaoConfig recordEntityDaoConfig;

    private final UserInfoEntityDao userInfoEntityDao;
    private final RecordEntityDao recordEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoEntityDaoConfig = daoConfigMap.get(UserInfoEntityDao.class).clone();
        userInfoEntityDaoConfig.initIdentityScope(type);

        recordEntityDaoConfig = daoConfigMap.get(RecordEntityDao.class).clone();
        recordEntityDaoConfig.initIdentityScope(type);

        userInfoEntityDao = new UserInfoEntityDao(userInfoEntityDaoConfig, this);
        recordEntityDao = new RecordEntityDao(recordEntityDaoConfig, this);

        registerDao(UserInfoEntity.class, userInfoEntityDao);
        registerDao(RecordEntity.class, recordEntityDao);
    }
    
    public void clear() {
        userInfoEntityDaoConfig.clearIdentityScope();
        recordEntityDaoConfig.clearIdentityScope();
    }

    public UserInfoEntityDao getUserInfoEntityDao() {
        return userInfoEntityDao;
    }

    public RecordEntityDao getRecordEntityDao() {
        return recordEntityDao;
    }

}
